### Create new game for maxPlayers number
POST http://localhost:3000/games
Content-Type: application/json

{
  "maxPlayer": 2
}

### Update game by ID
PATCH  http://localhost:3000/games/1
Content-Type: application/json

{
  "stoppedAt": "2023-09-01T09:30:45.842Z"
}