### Create new game for maxPlayers number
POST http://localhost:3000/games
Content-Type: application/json

{
  "maxPlayer": 2
}

### Update game by ID
PATCH  http://localhost:3000/games/1
Content-Type: application/json

{
  "stoppedAt": "2023-09-01T09:30:45.842Z"
}

### Get game info by ID
GET http://localhost:3000/games/3

### Get all games
GET http://localhost:3000/games


### Create new player
POST http://localhost:3000/players
Content-Type: application/json

{
  "nickName": "Player_1"
}

### Get player info by ID
GET http://localhost:3000/players/1

### Update player by ID
PATCH  http://localhost:3000/players/1
Content-Type: application/json

{
  "status": "playing",
  "numberInLine": 1,
  "nickName": "S_1"
}