### Create new game for maxPlayers number
POST http://localhost:3000/games
Content-Type: application/json

{
  "maxPlayer": 2
}

### Update game by ID
PATCH  http://localhost:3000/games/1
Content-Type: application/json

{
  "stoppedAt": "2023-09-01T09:30:45.842Z"
}

### Get game info by ID
GET http://localhost:3000/games/21

### Get all games
GET http://localhost:3000/games

### Get first available game
POST http://localhost:3000/games/available

### Start game
POST http://localhost:3000/games/26/start


### Stop game
POST http://localhost:3000/games/1/stop

### Add player to game
POST http://localhost:3000/games/4/add-player
Content-Type: application/json

{
  "playerId": 1
}

### Remove player from game
POST http://localhost:3000/games/3/remove-player
Content-Type: application/json

{
  "playerId": 1
}

### Make move
POST http://localhost:3000/games/make-move
Content-Type: application/json

{
  "game": 21,
  "player": 45
}

### Create new player
POST http://localhost:3000/players
Content-Type: application/json

{
  "nickName": "Player_1"
}

### Get player info by ID
GET http://localhost:3000/players/2

### Update player by ID
PATCH  http://localhost:3000/players/2
Content-Type: application/json

{
  "status": "waiting",
  "numberInLine": 1,
  "nickName": "S_1"
}

### Get all players
GET http://localhost:3000/players